### ISSUE TITLE
no update layout on delete one child

### ISSUE THREAD

**Issue by ghost** [neslib/Neslib.Yoga#1]
I noticed that when deleting an item from the middle, it is not recalculated to the positions of the other brothers

**Comment by ghost** [comment]
solution.....

procedure TTile.Remove;
begin
  **FNode.Parent.Remove(FNode);**

  if (Parent <> nil) then
    Parent.RemoveControl(Self);

  Free;
end;

**Comment by neslib** [comment]
Thanks for pointing this out. I just pushed your suggested fix.
